pub fn addCases(cases: *tests.LibcContext) void {
    cases.addLibcTestCase("api/main.c", .{});

    cases.addLibcTestCase("functional/argv.c", .{});
    cases.addLibcTestCase("functional/basename.c", .{});
    cases.addLibcTestCase("functional/clocale_mbfuncs.c", .{});
    cases.addLibcTestCase("functional/clock_gettime.c", .{});
    cases.addLibcTestCase("functional/crypt.c", .{});
    cases.addLibcTestCase("functional/dirname.c", .{});
    cases.addLibcTestCase("functional/env.c", .{});
    cases.addLibcTestCase("functional/fcntl.c", .{});
    cases.addLibcTestCase("functional/fdopen.c", .{});
    cases.addLibcTestCase("functional/fnmatch.c", .{});
    cases.addLibcTestCase("functional/fscanf.c", .{});
    cases.addLibcTestCase("functional/fwscanf.c", .{});
    cases.addLibcTestCase("functional/iconv_open.c", .{});
    cases.addLibcTestCase("functional/inet_pton.c", .{});
    // "functional/ipc_msg.c": Probably a bug in qemu
    // "functional/ipc_sem.c": Probably a bug in qemu
    // "functional/ipc_shm.c": Probably a bug in qemu
    cases.addLibcTestCase("functional/mbc.c", .{});
    cases.addLibcTestCase("functional/memstream.c", .{});
    // "functional/mntent.c": https://www.openwall.com/lists/musl/2024/10/22/1
    cases.addLibcTestCase("functional/popen.c", .{});
    // cases.addLibcTestCase("functional/pthread_cancel-points.c", .{}); - racey if multiple instances of the test run concurrently.
    cases.addLibcTestCase("functional/pthread_cancel.c", .{});
    cases.addLibcTestCase("functional/pthread_cond.c", .{});
    cases.addLibcTestCase("functional/pthread_mutex.c", .{});
    // "functional/pthread_mutex_pi.c": Probably a bug in qemu (big/little endian FUTEX_LOCK_PI)
    // "functional/pthread_robust.c": https://gitlab.com/qemu-project/qemu/-/issues/2424
    cases.addLibcTestCase("functional/pthread_tsd.c", .{});
    cases.addLibcTestCase("functional/qsort.c", .{});
    cases.addLibcTestCase("functional/random.c", .{});
    cases.addLibcTestCase("functional/search_hsearch.c", .{});
    cases.addLibcTestCase("functional/search_insque.c", .{});
    cases.addLibcTestCase("functional/search_lsearch.c", .{});
    cases.addLibcTestCase("functional/search_tsearch.c", .{});
    cases.addLibcTestCase("functional/sem_init.c", .{});
    cases.addLibcTestCase("functional/sem_open.c", .{});
    cases.addLibcTestCase("functional/setjmp.c", .{});
    cases.addLibcTestCase("functional/snprintf.c", .{});
    cases.addLibcTestCase("functional/socket.c", .{});
    cases.addLibcTestCase("functional/spawn.c", .{});
    cases.addLibcTestCase("functional/sscanf.c", .{});
    cases.addLibcTestCase("functional/sscanf_long.c", .{});
    cases.addLibcTestCase("functional/stat.c", .{});
    cases.addLibcTestCase("functional/strftime.c", .{});
    cases.addLibcTestCase("functional/string.c", .{});
    cases.addLibcTestCase("functional/string_memcpy.c", .{});
    cases.addLibcTestCase("functional/string_memmem.c", .{});
    cases.addLibcTestCase("functional/string_memset.c", .{});
    cases.addLibcTestCase("functional/string_strchr.c", .{});
    cases.addLibcTestCase("functional/string_strcspn.c", .{});
    cases.addLibcTestCase("functional/string_strstr.c", .{});
    cases.addLibcTestCase("functional/strtod.c", .{});
    cases.addLibcTestCase("functional/strtod_long.c", .{});
    cases.addLibcTestCase("functional/strtod_simple.c", .{});
    cases.addLibcTestCase("functional/strtof.c", .{});
    cases.addLibcTestCase("functional/strtol.c", .{});
    cases.addLibcTestCase("functional/strtold.c", .{});
    cases.addLibcTestCase("functional/swprintf.c", .{});
    cases.addLibcTestCase("functional/tgmath.c", .{});
    cases.addLibcTestCase("functional/time.c", .{});
    cases.addLibcTestCase("functional/tls_align.c", .{ .additional_src_file = "functional/tls_align_dso.c" });
    cases.addLibcTestCase("functional/tls_init.c", .{});
    cases.addLibcTestCase("functional/tls_local_exec.c", .{});
    cases.addLibcTestCase("functional/udiv.c", .{});
    cases.addLibcTestCase("functional/ungetc.c", .{});
    // cases.addLibcTestCase("functional/utime.c", .{}); - fails under heavy load; futimens not reflected in subsequent fstat
    cases.addLibcTestCase("functional/vfork.c", .{});
    cases.addLibcTestCase("functional/wcsstr.c", .{});
    cases.addLibcTestCase("functional/wcstol.c", .{});

    // cases.addLibcTestCase("regression/daemon-failure.c", .{}); - unexpected ENOMEM with high FD limit
    cases.addLibcTestCase("regression/dn_expand-empty.c", .{});
    cases.addLibcTestCase("regression/dn_expand-ptr-0.c", .{});
    cases.addLibcTestCase("regression/execle-env.c", .{});
    cases.addLibcTestCase("regression/fflush-exit.c", .{});
    cases.addLibcTestCase("regression/fgets-eof.c", .{});
    cases.addLibcTestCase("regression/fgetwc-buffering.c", .{});
    cases.addLibcTestCase("regression/flockfile-list.c", .{});
    cases.addLibcTestCase("regression/fpclassify-invalid-ld80.c", .{});
    cases.addLibcTestCase("regression/ftello-unflushed-append.c", .{});
    cases.addLibcTestCase("regression/getpwnam_r-crash.c", .{});
    cases.addLibcTestCase("regression/getpwnam_r-errno.c", .{});
    cases.addLibcTestCase("regression/iconv-roundtrips.c", .{});
    cases.addLibcTestCase("regression/inet_ntop-v4mapped.c", .{});
    cases.addLibcTestCase("regression/inet_pton-empty-last-field.c", .{});
    cases.addLibcTestCase("regression/iswspace-null.c", .{});
    cases.addLibcTestCase("regression/lrand48-signextend.c", .{});
    cases.addLibcTestCase("regression/lseek-large.c", .{});
    cases.addLibcTestCase("regression/malloc-0.c", .{});
    // "regression/malloc-brk-fail.c": QEMU OOM
    // cases.addLibcTestCase("regression/malloc-oom.c", .{}); // QEMU OOM
    cases.addLibcTestCase("regression/mbsrtowcs-overflow.c", .{});
    cases.addLibcTestCase("regression/memmem-oob-read.c", .{});
    cases.addLibcTestCase("regression/memmem-oob.c", .{});
    cases.addLibcTestCase("regression/mkdtemp-failure.c", .{});
    cases.addLibcTestCase("regression/mkstemp-failure.c", .{});
    cases.addLibcTestCase("regression/printf-1e9-oob.c", .{});
    cases.addLibcTestCase("regression/printf-fmt-g-round.c", .{});
    cases.addLibcTestCase("regression/printf-fmt-g-zeros.c", .{});
    cases.addLibcTestCase("regression/printf-fmt-n.c", .{});
    // "regression/pthread-robust-detach.c": https://gitlab.com/qemu-project/qemu/-/issues/2424
    cases.addLibcTestCase("regression/pthread_atfork-errno-clobber.c", .{});
    cases.addLibcTestCase("regression/pthread_cancel-sem_wait.c", .{});
    // Flaky under heavy load: cases.addLibcTestCase("regression/pthread_cond-smasher.c", .{});
    // Flaky under heavy load: cases.addLibcTestCase("regression/pthread_cond_wait-cancel_ignored.c", .{});
    cases.addLibcTestCase("regression/pthread_condattr_setclock.c", .{});
    // "regression/pthread_create-oom.c": QEMU OOM
    cases.addLibcTestCase("regression/pthread_exit-cancel.c", .{});
    cases.addLibcTestCase("regression/pthread_exit-dtor.c", .{});
    cases.addLibcTestCase("regression/pthread_once-deadlock.c", .{});
    cases.addLibcTestCase("regression/pthread_rwlock-ebusy.c", .{});
    cases.addLibcTestCase("regression/putenv-doublefree.c", .{});
    // cases.addLibcTestCase("regression/raise-race.c", .{}); - Sometimes hangs when run natively on x86_64-linux.
    cases.addLibcTestCase("regression/regex-backref-0.c", .{});
    cases.addLibcTestCase("regression/regex-bracket-icase.c", .{});
    cases.addLibcTestCase("regression/regex-ere-backref.c", .{});
    cases.addLibcTestCase("regression/regex-escaped-high-byte.c", .{});
    cases.addLibcTestCase("regression/regex-negated-range.c", .{});
    cases.addLibcTestCase("regression/regexec-nosub.c", .{});
    cases.addLibcTestCase("regression/rewind-clear-error.c", .{});
    // cases.addLibcTestCase("regression/rlimit-open-files.c", .{}); - fails when machine is under heavy load
    cases.addLibcTestCase("regression/scanf-bytes-consumed.c", .{});
    cases.addLibcTestCase("regression/scanf-match-literal-eof.c", .{});
    cases.addLibcTestCase("regression/scanf-nullbyte-char.c", .{});
    cases.addLibcTestCase("regression/sem_close-unmap.c", .{});
    // "regression/setenv-oom.c": QEMU OOM
    cases.addLibcTestCase("regression/setvbuf-unget.c", .{});
    cases.addLibcTestCase("regression/sigaltstack.c", .{});
    cases.addLibcTestCase("regression/sigprocmask-internal.c", .{});
    cases.addLibcTestCase("regression/sigreturn.c", .{});
    cases.addLibcTestCase("regression/sscanf-eof.c", .{});
    cases.addLibcTestCase("regression/strverscmp.c", .{});
    cases.addLibcTestCase("regression/syscall-sign-extend.c", .{});
    cases.addLibcTestCase("regression/uselocale-0.c", .{});
    cases.addLibcTestCase("regression/wcsncpy-read-overflow.c", .{});
    cases.addLibcTestCase("regression/wcsstr-false-negative.c", .{});

    cases.addLibcTestCase("math/acos.c", .{});
    cases.addLibcTestCase("math/acosf.c", .{});
    // cases.addLibcTestCase("math/acosh.c", .{});
    cases.addLibcTestCase("math/acoshf.c", .{});
    // cases.addLibcTestCase("math/acoshl.c", .{});
    // cases.addLibcTestCase("math/acosl.c", .{});
    cases.addLibcTestCase("math/asin.c", .{});
    cases.addLibcTestCase("math/asinf.c", .{});
    // cases.addLibcTestCase("math/asinh.c", .{});
    cases.addLibcTestCase("math/asinhf.c", .{});
    // cases.addLibcTestCase("math/asinhl.c", .{});
    cases.addLibcTestCase("math/asinl.c", .{});
    cases.addLibcTestCase("math/atan.c", .{});
    cases.addLibcTestCase("math/atan2.c", .{});
    cases.addLibcTestCase("math/atan2f.c", .{});
    cases.addLibcTestCase("math/atan2l.c", .{});
    cases.addLibcTestCase("math/atanf.c", .{});
    cases.addLibcTestCase("math/atanh.c", .{});
    cases.addLibcTestCase("math/atanhf.c", .{});
    cases.addLibcTestCase("math/atanhl.c", .{});
    cases.addLibcTestCase("math/atanl.c", .{});
    cases.addLibcTestCase("math/cbrt.c", .{});
    cases.addLibcTestCase("math/cbrtf.c", .{});
    cases.addLibcTestCase("math/cbrtl.c", .{});
    cases.addLibcTestCase("math/ceil.c", .{});
    cases.addLibcTestCase("math/ceilf.c", .{});
    cases.addLibcTestCase("math/ceill.c", .{});
    cases.addLibcTestCase("math/copysign.c", .{});
    cases.addLibcTestCase("math/copysignf.c", .{});
    cases.addLibcTestCase("math/copysignl.c", .{});
    cases.addLibcTestCase("math/cos.c", .{});
    cases.addLibcTestCase("math/cosf.c", .{});
    cases.addLibcTestCase("math/cosh.c", .{});
    cases.addLibcTestCase("math/coshf.c", .{});
    cases.addLibcTestCase("math/coshl.c", .{});
    cases.addLibcTestCase("math/cosl.c", .{});
    cases.addLibcTestCase("math/drem.c", .{});
    cases.addLibcTestCase("math/dremf.c", .{});
    cases.addLibcTestCase("math/erf.c", .{});
    cases.addLibcTestCase("math/erfc.c", .{});
    // cases.addLibcTestCase("math/erfcf.c", .{});
    cases.addLibcTestCase("math/erfcl.c", .{});
    cases.addLibcTestCase("math/erff.c", .{});
    cases.addLibcTestCase("math/erfl.c", .{});
    cases.addLibcTestCase("math/exp.c", .{});
    cases.addLibcTestCase("math/exp10.c", .{});
    cases.addLibcTestCase("math/exp10f.c", .{});
    cases.addLibcTestCase("math/exp10l.c", .{});
    cases.addLibcTestCase("math/exp2.c", .{});
    cases.addLibcTestCase("math/exp2f.c", .{});
    cases.addLibcTestCase("math/exp2l.c", .{});
    cases.addLibcTestCase("math/expf.c", .{});
    // cases.addLibcTestCase("math/expl.c", .{});
    // cases.addLibcTestCase("math/expm1.c", .{});
    // cases.addLibcTestCase("math/expm1f.c", .{});
    // cases.addLibcTestCase("math/expm1l.c", .{});
    cases.addLibcTestCase("math/fabs.c", .{});
    cases.addLibcTestCase("math/fabsf.c", .{});
    cases.addLibcTestCase("math/fabsl.c", .{});
    cases.addLibcTestCase("math/fdim.c", .{});
    cases.addLibcTestCase("math/fdimf.c", .{});
    cases.addLibcTestCase("math/fdiml.c", .{});
    cases.addLibcTestCase("math/fenv.c", .{});
    cases.addLibcTestCase("math/floor.c", .{});
    cases.addLibcTestCase("math/floorf.c", .{});
    cases.addLibcTestCase("math/floorl.c", .{});
    // cases.addLibcTestCase("math/fma.c", .{});
    // cases.addLibcTestCase("math/fmaf.c", .{});
    // cases.addLibcTestCase("math/fmal.c", .{});
    cases.addLibcTestCase("math/fmax.c", .{});
    cases.addLibcTestCase("math/fmaxf.c", .{});
    cases.addLibcTestCase("math/fmaxl.c", .{});
    cases.addLibcTestCase("math/fmin.c", .{});
    cases.addLibcTestCase("math/fminf.c", .{});
    cases.addLibcTestCase("math/fminl.c", .{});
    cases.addLibcTestCase("math/fmod.c", .{});
    cases.addLibcTestCase("math/fmodf.c", .{});
    cases.addLibcTestCase("math/fmodl.c", .{});
    cases.addLibcTestCase("math/fpclassify.c", .{});
    cases.addLibcTestCase("math/frexp.c", .{});
    cases.addLibcTestCase("math/frexpf.c", .{});
    cases.addLibcTestCase("math/frexpl.c", .{});
    cases.addLibcTestCase("math/hypot.c", .{});
    cases.addLibcTestCase("math/hypotf.c", .{});
    cases.addLibcTestCase("math/hypotl.c", .{});
    // cases.addLibcTestCase("math/ilogb.c", .{});
    // cases.addLibcTestCase("math/ilogbf.c", .{});
    // cases.addLibcTestCase("math/ilogbl.c", .{});
    cases.addLibcTestCase("math/isless.c", .{});
    // cases.addLibcTestCase("math/j0.c", .{});
    cases.addLibcTestCase("math/j0f.c", .{});
    cases.addLibcTestCase("math/j1.c", .{});
    cases.addLibcTestCase("math/j1f.c", .{});
    // cases.addLibcTestCase("math/jn.c", .{});
    // cases.addLibcTestCase("math/jnf.c", .{});
    cases.addLibcTestCase("math/ldexp.c", .{});
    cases.addLibcTestCase("math/ldexpf.c", .{});
    cases.addLibcTestCase("math/ldexpl.c", .{});
    // cases.addLibcTestCase("math/lgamma.c", .{});
    cases.addLibcTestCase("math/lgamma_r.c", .{});
    // cases.addLibcTestCase("math/lgammaf.c", .{});
    // cases.addLibcTestCase("math/lgammaf_r.c", .{});
    // cases.addLibcTestCase("math/lgammal.c", .{});
    cases.addLibcTestCase("math/lgammal_r.c", .{});
    // cases.addLibcTestCase("math/llrint.c", .{});
    // cases.addLibcTestCase("math/llrintf.c", .{});
    // cases.addLibcTestCase("math/llrintl.c", .{});
    // cases.addLibcTestCase("math/llround.c", .{});
    // cases.addLibcTestCase("math/llroundf.c", .{});
    // cases.addLibcTestCase("math/llroundl.c", .{});
    cases.addLibcTestCase("math/log.c", .{});
    cases.addLibcTestCase("math/log10.c", .{});
    cases.addLibcTestCase("math/log10f.c", .{});
    cases.addLibcTestCase("math/log10l.c", .{});
    cases.addLibcTestCase("math/log1p.c", .{});
    cases.addLibcTestCase("math/log1pf.c", .{});
    // cases.addLibcTestCase("math/log1pl.c", .{});
    cases.addLibcTestCase("math/log2.c", .{});
    cases.addLibcTestCase("math/log2f.c", .{});
    cases.addLibcTestCase("math/log2l.c", .{});
    // cases.addLibcTestCase("math/logb.c", .{});
    // cases.addLibcTestCase("math/logbf.c", .{});
    // cases.addLibcTestCase("math/logbl.c", .{});
    cases.addLibcTestCase("math/logf.c", .{});
    cases.addLibcTestCase("math/logl.c", .{});
    cases.addLibcTestCase("math/lrint.c", .{});
    cases.addLibcTestCase("math/lrintf.c", .{});
    cases.addLibcTestCase("math/lrintl.c", .{});
    cases.addLibcTestCase("math/lround.c", .{});
    cases.addLibcTestCase("math/lroundf.c", .{});
    cases.addLibcTestCase("math/lroundl.c", .{});
    cases.addLibcTestCase("math/modf.c", .{});
    cases.addLibcTestCase("math/modff.c", .{});
    cases.addLibcTestCase("math/modfl.c", .{});
    // cases.addLibcTestCase("math/nearbyint.c", .{});
    cases.addLibcTestCase("math/nearbyintf.c", .{});
    // cases.addLibcTestCase("math/nearbyintl.c", .{});
    cases.addLibcTestCase("math/nextafter.c", .{});
    cases.addLibcTestCase("math/nextafterf.c", .{});
    cases.addLibcTestCase("math/nextafterl.c", .{});
    cases.addLibcTestCase("math/nexttoward.c", .{});
    cases.addLibcTestCase("math/nexttowardf.c", .{});
    cases.addLibcTestCase("math/nexttowardl.c", .{});
    // cases.addLibcTestCase("math/pow.c", .{});
    cases.addLibcTestCase("math/pow10.c", .{});
    cases.addLibcTestCase("math/pow10f.c", .{});
    cases.addLibcTestCase("math/pow10l.c", .{});
    // cases.addLibcTestCase("math/powf.c", .{});
    // cases.addLibcTestCase("math/powl.c", .{});
    cases.addLibcTestCase("math/remainder.c", .{});
    cases.addLibcTestCase("math/remainderf.c", .{});
    cases.addLibcTestCase("math/remainderl.c", .{});
    cases.addLibcTestCase("math/remquo.c", .{});
    cases.addLibcTestCase("math/remquof.c", .{});
    cases.addLibcTestCase("math/remquol.c", .{});
    cases.addLibcTestCase("math/rint.c", .{});
    cases.addLibcTestCase("math/rintf.c", .{});
    cases.addLibcTestCase("math/rintl.c", .{});
    cases.addLibcTestCase("math/round.c", .{});
    cases.addLibcTestCase("math/roundf.c", .{});
    cases.addLibcTestCase("math/roundl.c", .{});
    cases.addLibcTestCase("math/scalb.c", .{});
    cases.addLibcTestCase("math/scalbf.c", .{});
    cases.addLibcTestCase("math/scalbln.c", .{});
    cases.addLibcTestCase("math/scalblnf.c", .{});
    cases.addLibcTestCase("math/scalblnl.c", .{});
    cases.addLibcTestCase("math/scalbn.c", .{});
    cases.addLibcTestCase("math/scalbnf.c", .{});
    cases.addLibcTestCase("math/scalbnl.c", .{});
    cases.addLibcTestCase("math/sin.c", .{});
    cases.addLibcTestCase("math/sincos.c", .{});
    cases.addLibcTestCase("math/sincosf.c", .{});
    cases.addLibcTestCase("math/sincosl.c", .{});
    cases.addLibcTestCase("math/sinf.c", .{});
    // cases.addLibcTestCase("math/sinh.c", .{});
    cases.addLibcTestCase("math/sinhf.c", .{});
    // cases.addLibcTestCase("math/sinhl.c", .{});
    cases.addLibcTestCase("math/sinl.c", .{});
    cases.addLibcTestCase("math/sqrt.c", .{});
    cases.addLibcTestCase("math/sqrtf.c", .{});
    cases.addLibcTestCase("math/sqrtl.c", .{});
    cases.addLibcTestCase("math/tan.c", .{});
    cases.addLibcTestCase("math/tanf.c", .{});
    cases.addLibcTestCase("math/tanh.c", .{});
    cases.addLibcTestCase("math/tanhf.c", .{});
    cases.addLibcTestCase("math/tanhl.c", .{});
    cases.addLibcTestCase("math/tanl.c", .{});
    // cases.addLibcTestCase("math/tgamma.c", .{});
    // cases.addLibcTestCase("math/tgammaf.c", .{});
    // cases.addLibcTestCase("math/tgammal.c", .{});
    cases.addLibcTestCase("math/trunc.c", .{});
    cases.addLibcTestCase("math/truncf.c", .{});
    cases.addLibcTestCase("math/truncl.c", .{});
    // cases.addLibcTestCase("math/y0.c", .{});
    // cases.addLibcTestCase("math/y0f.c", .{});
    // cases.addLibcTestCase("math/y1.c", .{});
    // cases.addLibcTestCase("math/y1f.c", .{});
    // cases.addLibcTestCase("math/yn.c", .{});
    // cases.addLibcTestCase("math/ynf.c", .{});
}

const std = @import("std");
const tests = @import("tests.zig");
