name: Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build-check-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    # Forces all steps in this job to use bash, even on Windows
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5

      - uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Run zig build check test
        run: ZIG_DEBUG_MAKER=TRUE ZIG_LIB_DIR=./lib zig build check test --summary all
